# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
        ('users', '0002_auto_20160715_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='states.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
