# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_to_benevity',
            field=models.BooleanField(default=False),
        ),
    ]
