# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160722_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tax_receipts_as',
            field=models.IntegerField(choices=[(1, b'User'), (2, b'Company')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default=-333, max_length=10),
            preserve_default=False,
        ),
    ]
