# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160908_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='free_trial_started_at',
        ),
    ]
