# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160727_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='status',
            field=models.CharField(choices=[(b'A', b'Accepted'), (b'R', b'Rejected'), (b'W', b'Waiting')], default=b'W', max_length=1),
        ),
    ]
