# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_userevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='status',
            field=models.CharField(choices=[(b'A', b'ACCEPTED'), (b'R', b'REJECTED'), (b'W', b'WAITING')], default=b'W', max_length=1),
        ),
    ]
