# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160729_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='status',
            field=models.CharField(choices=[(b'A', b'ACCEPTED'), (b'R', b'REJECTED'), (b'W', b'WAITING'), (b'V', b'VIEWED')], default=b'W', max_length=1),
        ),
    ]
