# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refno_benevity',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
