# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycountry',
            name='picture',
            field=models.ImageField(default=None, upload_to=b'charities/%Y/%m'),
            preserve_default=False,
        ),
    ]
