# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 23:39
from __future__ import unicode_literals

import charities.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charitycountry_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitycountry',
            name='picture',
            field=models.ImageField(upload_to=charities.helpers.PathAndRename(b'charities')),
        ),
    ]
