# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_auto_20160801_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycountry',
            name='benevity_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
