# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default=124, max_length=3),
            preserve_default=False,
        ),
    ]
