# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxreceipt',
            old_name='description',
            new_name='name',
        ),
    ]
