# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0002_customerstripe_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
